/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CanvasBox: typeof import('./src/components/canvas-box/CanvasBox.vue')['default']
    CanvasEditor: typeof import('./src/components/canvas-box/CanvasEditor.vue')['default']
    CanvasFooter: typeof import('./src/components/canvas-footer/CanvasFooter.vue')['default']
    ComponentData: typeof import('./src/components/sidebar-component/ComponentData.vue')['default']
    ComponentEvent: typeof import('./src/components/sidebar-component/ComponentEvent.vue')['default']
    ComponentProperty: typeof import('./src/components/sidebar-component/ComponentProperty.vue')['default']
    NavigationView: typeof import('./src/components/Navigation/NavigationView.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapeBox: typeof import('./src/components/canvas-box/ShapeBox.vue')['default']
    SidebarComponent: typeof import('./src/components/sidebar-component/SidebarComponent.vue')['default']
    SidebarList: typeof import('./src/components/sidebar-list/SidebarList.vue')['default']
    SwitchLanguage: typeof import('./src/components/Navigation/SwitchLanguage.vue')['default']
    ThemeButton: typeof import('./src/components/Navigation/ThemeButton.vue')['default']
    VirtualList: typeof import('./src/components/sidebar-list/VirtualList.vue')['default']
  }
}
