// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		CodeEditor: typeof import('./src/components/CodeEditor.vue')['default'];
		ElButton: typeof import('element-plus/es')['ElButton'];
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
		ElDialog: typeof import('element-plus/es')['ElDialog'];
		ElIcon: typeof import('element-plus/es')['ElIcon'];
		ElInput: typeof import('element-plus/es')['ElInput'];
		ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
		ElOption: typeof import('element-plus/es')['ElOption'];
		ElSelect: typeof import('element-plus/es')['ElSelect'];
		ElSwitch: typeof import('element-plus/es')['ElSwitch'];
		ElTabPane: typeof import('element-plus/es')['ElTabPane'];
		ElTabs: typeof import('element-plus/es')['ElTabs'];
		ElUpload: typeof import('element-plus/es')['ElUpload'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		VirtualList: typeof import('./src/components/VirtualList.vue')['default'];
	}
}
