// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		DuiInput: typeof import('./src/components/dui-input/DuiInput.vue')['default'];
		ElInput: typeof import('element-plus/es')['ElInput'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
